/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author LSA
 */
public class TelaDiretor extends javax.swing.JFrame {
   private Point point = new Point();
    /**
     * Creates new form TelaDiretor
     */
    public TelaDiretor() {
        initComponents();
        this.setIconImage( new ImageIcon(getClass().getResource("/Imagens/logoSDi.png")).getImage());
    }

    public void setCorPanel(JPanel p, JLabel l){
        
     p.setBackground(new Color (115,163,239));
     l.setForeground(new Color(255,255,255));
    }
    
     public void resetCorPanel(JPanel p,JLabel l){
        
     p.setBackground(new Color (240,240,240));
     l.setForeground(new Color(0,0,0));
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        pCadastrarUsuario = new javax.swing.JPanel();
        lCadastrarUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pGerirSolicitacoes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lSolicitarNoticia = new javax.swing.JLabel();
        pEnviar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lEnviar = new javax.swing.JLabel();
        pAlterarSenha = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lAlterarSenha = new javax.swing.JLabel();
        pLogOut = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lLogOut = new javax.swing.JLabel();
        pSobre = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lSobre = new javax.swing.JLabel();
        pCadastrarServidor = new javax.swing.JPanel();
        lCadastrarServidor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pCadastrarCampus = new javax.swing.JPanel();
        lCadastrarCampus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pSair1 = new javax.swing.JPanel();
        lSair1 = new javax.swing.JLabel();
        pMinimizar = new javax.swing.JPanel();
        lMinimizar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SDi - Tela Inicial Diretor");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(150, 125));

        pCadastrarUsuario.setEnabled(false);
        pCadastrarUsuario.setPreferredSize(new java.awt.Dimension(150, 125));
        pCadastrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCadastrarUsuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCadastrarUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCadastrarUsuarioMouseExited(evt);
            }
        });

        lCadastrarUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lCadastrarUsuario.setText("Cadastrar Usuário");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Administrator_Male_64px_2.png"))); // NOI18N

        javax.swing.GroupLayout pCadastrarUsuarioLayout = new javax.swing.GroupLayout(pCadastrarUsuario);
        pCadastrarUsuario.setLayout(pCadastrarUsuarioLayout);
        pCadastrarUsuarioLayout.setHorizontalGroup(
            pCadastrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarUsuarioLayout.createSequentialGroup()
                .addGroup(pCadastrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pCadastrarUsuarioLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(pCadastrarUsuarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lCadastrarUsuario)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pCadastrarUsuarioLayout.setVerticalGroup(
            pCadastrarUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarUsuarioLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lCadastrarUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pGerirSolicitacoes.setPreferredSize(new java.awt.Dimension(150, 125));
        pGerirSolicitacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pGerirSolicitacoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pGerirSolicitacoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pGerirSolicitacoesMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Ask_Question_64px.png"))); // NOI18N

        lSolicitarNoticia.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lSolicitarNoticia.setText("Gerir Solicitações");

        javax.swing.GroupLayout pGerirSolicitacoesLayout = new javax.swing.GroupLayout(pGerirSolicitacoes);
        pGerirSolicitacoes.setLayout(pGerirSolicitacoesLayout);
        pGerirSolicitacoesLayout.setHorizontalGroup(
            pGerirSolicitacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGerirSolicitacoesLayout.createSequentialGroup()
                .addGroup(pGerirSolicitacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGerirSolicitacoesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7))
                    .addGroup(pGerirSolicitacoesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lSolicitarNoticia)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pGerirSolicitacoesLayout.setVerticalGroup(
            pGerirSolicitacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGerirSolicitacoesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lSolicitarNoticia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pEnviar.setPreferredSize(new java.awt.Dimension(150, 125));
        pEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pEnviarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pEnviarMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_News_64px_1.png"))); // NOI18N

        lEnviar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lEnviar.setText("Gerir Notícias");

        javax.swing.GroupLayout pEnviarLayout = new javax.swing.GroupLayout(pEnviar);
        pEnviar.setLayout(pEnviarLayout);
        pEnviarLayout.setHorizontalGroup(
            pEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnviarLayout.createSequentialGroup()
                .addGroup(pEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEnviarLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8))
                    .addGroup(pEnviarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lEnviar)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pEnviarLayout.setVerticalGroup(
            pEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEnviarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pAlterarSenha.setPreferredSize(new java.awt.Dimension(150, 125));
        pAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAlterarSenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pAlterarSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pAlterarSenhaMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Key_64px_2.png"))); // NOI18N

        lAlterarSenha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lAlterarSenha.setText("Alterar Senha");

        javax.swing.GroupLayout pAlterarSenhaLayout = new javax.swing.GroupLayout(pAlterarSenha);
        pAlterarSenha.setLayout(pAlterarSenhaLayout);
        pAlterarSenhaLayout.setHorizontalGroup(
            pAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlterarSenhaLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(pAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlterarSenhaLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlterarSenhaLayout.createSequentialGroup()
                        .addComponent(lAlterarSenha)
                        .addGap(25, 25, 25))))
        );
        pAlterarSenhaLayout.setVerticalGroup(
            pAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlterarSenhaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAlterarSenha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pLogOut.setPreferredSize(new java.awt.Dimension(150, 125));
        pLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pLogOutMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Sign_Out_64px_1.png"))); // NOI18N

        lLogOut.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lLogOut.setText("Log Out");

        javax.swing.GroupLayout pLogOutLayout = new javax.swing.GroupLayout(pLogOut);
        pLogOut.setLayout(pLogOutLayout);
        pLogOutLayout.setHorizontalGroup(
            pLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLogOutLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(pLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lLogOut))
                .addGap(38, 38, 38))
        );
        pLogOutLayout.setVerticalGroup(
            pLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogOutLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lLogOut)
                .addContainerGap())
        );

        pSobre.setPreferredSize(new java.awt.Dimension(150, 125));
        pSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSobreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pSobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pSobreMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Info_64px.png"))); // NOI18N

        lSobre.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lSobre.setText("Sobre");

        javax.swing.GroupLayout pSobreLayout = new javax.swing.GroupLayout(pSobre);
        pSobre.setLayout(pSobreLayout);
        pSobreLayout.setHorizontalGroup(
            pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSobreLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSobreLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lSobre))
                    .addComponent(jLabel6))
                .addGap(42, 42, 42))
        );
        pSobreLayout.setVerticalGroup(
            pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSobreLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSobre)
                .addContainerGap())
        );

        pCadastrarServidor.setEnabled(false);
        pCadastrarServidor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCadastrarServidorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCadastrarServidorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCadastrarServidorMouseExited(evt);
            }
        });

        lCadastrarServidor.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lCadastrarServidor.setText("Cadastrar Servidor");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_User_64px_2.png"))); // NOI18N

        javax.swing.GroupLayout pCadastrarServidorLayout = new javax.swing.GroupLayout(pCadastrarServidor);
        pCadastrarServidor.setLayout(pCadastrarServidorLayout);
        pCadastrarServidorLayout.setHorizontalGroup(
            pCadastrarServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarServidorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lCadastrarServidor)
                .addContainerGap())
            .addGroup(pCadastrarServidorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastrarServidorLayout.setVerticalGroup(
            pCadastrarServidorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarServidorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lCadastrarServidor)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pCadastrarCampus.setEnabled(false);
        pCadastrarCampus.setPreferredSize(new java.awt.Dimension(150, 125));
        pCadastrarCampus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pCadastrarCampusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pCadastrarCampusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pCadastrarCampusMouseExited(evt);
            }
        });

        lCadastrarCampus.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lCadastrarCampus.setText("Cadastrar Campus");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Graduation_Cap_64px_1.png"))); // NOI18N

        javax.swing.GroupLayout pCadastrarCampusLayout = new javax.swing.GroupLayout(pCadastrarCampus);
        pCadastrarCampus.setLayout(pCadastrarCampusLayout);
        pCadastrarCampusLayout.setHorizontalGroup(
            pCadastrarCampusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarCampusLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(lCadastrarCampus)
                .addContainerGap())
            .addGroup(pCadastrarCampusLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pCadastrarCampusLayout.setVerticalGroup(
            pCadastrarCampusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pCadastrarCampusLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lCadastrarCampus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        pSair1.setBackground(new java.awt.Color(0, 51, 255));
        pSair1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSair1MouseClicked(evt);
            }
        });

        lSair1.setBackground(new java.awt.Color(255, 0, 0));
        lSair1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lSair1.setForeground(new java.awt.Color(255, 255, 255));
        lSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Delete_20px.png"))); // NOI18N
        lSair1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSair1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lSair1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lSair1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pSair1Layout = new javax.swing.GroupLayout(pSair1);
        pSair1.setLayout(pSair1Layout);
        pSair1Layout.setHorizontalGroup(
            pSair1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSair1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lSair1))
        );
        pSair1Layout.setVerticalGroup(
            pSair1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lSair1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pMinimizar.setBackground(new java.awt.Color(0, 51, 255));
        pMinimizar.setPreferredSize(new java.awt.Dimension(20, 20));
        pMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMinimizarMouseExited(evt);
            }
        });

        lMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Horizontal_Line_20px_4.png"))); // NOI18N

        javax.swing.GroupLayout pMinimizarLayout = new javax.swing.GroupLayout(pMinimizar);
        pMinimizar.setLayout(pMinimizarLayout);
        pMinimizarLayout.setHorizontalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );
        pMinimizarLayout.setVerticalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tela Inicial");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/teste3.png"))); // NOI18N
        jLabel11.setFocusCycleRoot(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(pSair1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pSair1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel4))
            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(pAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pCadastrarServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pCadastrarCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(pLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pCadastrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pGerirSolicitacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pGerirSolicitacoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCadastrarServidor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCadastrarCampus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pCadastrarUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pCadastrarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarUsuarioMouseEntered
         setCorPanel(pCadastrarUsuario,lCadastrarUsuario);
    }//GEN-LAST:event_pCadastrarUsuarioMouseEntered

    private void pCadastrarUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarUsuarioMouseExited
         resetCorPanel(pCadastrarUsuario,lCadastrarUsuario);
    }//GEN-LAST:event_pCadastrarUsuarioMouseExited

    private void pCadastrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarUsuarioMouseClicked
        TelaCadastroUsuario obj = new TelaCadastroUsuario();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pCadastrarUsuarioMouseClicked

    private void pGerirSolicitacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGerirSolicitacoesMouseEntered
        setCorPanel(pGerirSolicitacoes,lSolicitarNoticia);
    }//GEN-LAST:event_pGerirSolicitacoesMouseEntered

    private void pGerirSolicitacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGerirSolicitacoesMouseExited
         resetCorPanel(pGerirSolicitacoes,lSolicitarNoticia);
    }//GEN-LAST:event_pGerirSolicitacoesMouseExited

    private void pEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEnviarMouseEntered
        setCorPanel(pEnviar,lEnviar);
    }//GEN-LAST:event_pEnviarMouseEntered

    private void pEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEnviarMouseExited
        resetCorPanel(pEnviar,lEnviar);
    }//GEN-LAST:event_pEnviarMouseExited

    private void pAlterarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAlterarSenhaMouseEntered
        setCorPanel(pAlterarSenha,lAlterarSenha);
    }//GEN-LAST:event_pAlterarSenhaMouseEntered

    private void pAlterarSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAlterarSenhaMouseExited
       resetCorPanel(pAlterarSenha,lAlterarSenha);
    }//GEN-LAST:event_pAlterarSenhaMouseExited

    private void pSobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSobreMouseEntered
        setCorPanel(pSobre,lSobre);
    }//GEN-LAST:event_pSobreMouseEntered

    private void pSobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSobreMouseExited
       resetCorPanel(pSobre,lSobre);
    }//GEN-LAST:event_pSobreMouseExited

    private void pLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLogOutMouseEntered
        setCorPanel(pLogOut,lLogOut);
    }//GEN-LAST:event_pLogOutMouseEntered

    private void pLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLogOutMouseExited
         resetCorPanel(pLogOut,lLogOut);
    }//GEN-LAST:event_pLogOutMouseExited

    private void pCadastrarServidorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarServidorMouseClicked
        TelaCadastroServidor obj = new TelaCadastroServidor();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pCadastrarServidorMouseClicked

    private void pCadastrarServidorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarServidorMouseEntered
        setCorPanel(pCadastrarServidor,lCadastrarServidor);
    }//GEN-LAST:event_pCadastrarServidorMouseEntered

    private void pCadastrarServidorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarServidorMouseExited
        resetCorPanel(pCadastrarServidor,lCadastrarServidor);
    }//GEN-LAST:event_pCadastrarServidorMouseExited

    private void pCadastrarCampusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarCampusMouseClicked
        TelaCadastroCampus obj = new TelaCadastroCampus();
        obj.setVisible(true);
        TelaCadastroCampus.voltarPara = "principal";
        this.dispose();
    }//GEN-LAST:event_pCadastrarCampusMouseClicked

    private void pCadastrarCampusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarCampusMouseEntered
        setCorPanel(pCadastrarCampus,lCadastrarCampus);
    }//GEN-LAST:event_pCadastrarCampusMouseEntered

    private void pCadastrarCampusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pCadastrarCampusMouseExited
        resetCorPanel(pCadastrarCampus,lCadastrarCampus);
    }//GEN-LAST:event_pCadastrarCampusMouseExited

    private void pGerirSolicitacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pGerirSolicitacoesMouseClicked
        TelaGerirSolicitacoes obj = new TelaGerirSolicitacoes();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pGerirSolicitacoesMouseClicked

    private void pEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEnviarMouseClicked
        TelaGerenciarNoticias obj = new TelaGerenciarNoticias();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pEnviarMouseClicked

    private void pAlterarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAlterarSenhaMouseClicked
        TelaAlterarSenha obj = new TelaAlterarSenha();
        obj.setVisible(true);
    }//GEN-LAST:event_pAlterarSenhaMouseClicked

    private void pSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSobreMouseClicked
        TelaSobre obj = new TelaSobre();
        obj.setVisible(true);
    }//GEN-LAST:event_pSobreMouseClicked

    private void pLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLogOutMouseClicked
        TelaLogin.senhaAtual = "";
        TelaLogin.loginAtual = "";
        TelaLogin obj = new TelaLogin();
        this.dispose();
        obj.setVisible(true);     
    }//GEN-LAST:event_pLogOutMouseClicked

    private void lSair1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSair1MouseClicked
        this.dispose();
    }//GEN-LAST:event_lSair1MouseClicked

    private void lSair1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSair1MouseEntered
        pSair1.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_lSair1MouseEntered

    private void lSair1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSair1MouseExited
        pSair1.setBackground(new Color(0,51,255));
    }//GEN-LAST:event_lSair1MouseExited

    private void pSair1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSair1MouseClicked
        this.dispose();
    }//GEN-LAST:event_pSair1MouseClicked

    private void pMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseClicked
        this.setState(TelaDiretor.ICONIFIED);
    }//GEN-LAST:event_pMinimizarMouseClicked

    private void pMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseEntered
        pMinimizar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_pMinimizarMouseEntered

    private void pMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseExited
        pMinimizar.setBackground(new Color(0,51,255));
    }//GEN-LAST:event_pMinimizarMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       point.x = evt.getX();
       point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDiretor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDiretor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lAlterarSenha;
    private javax.swing.JLabel lCadastrarCampus;
    private javax.swing.JLabel lCadastrarServidor;
    private javax.swing.JLabel lCadastrarUsuario;
    private javax.swing.JLabel lEnviar;
    private javax.swing.JLabel lLogOut;
    private javax.swing.JLabel lMinimizar;
    private javax.swing.JLabel lSair1;
    private javax.swing.JLabel lSobre;
    private javax.swing.JLabel lSolicitarNoticia;
    private javax.swing.JPanel pAlterarSenha;
    private javax.swing.JPanel pCadastrarCampus;
    private javax.swing.JPanel pCadastrarServidor;
    private javax.swing.JPanel pCadastrarUsuario;
    private javax.swing.JPanel pEnviar;
    private javax.swing.JPanel pGerirSolicitacoes;
    private javax.swing.JPanel pLogOut;
    private javax.swing.JPanel pMinimizar;
    private javax.swing.JPanel pSair1;
    private javax.swing.JPanel pSobre;
    // End of variables declaration//GEN-END:variables
}
