/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.CampusDAO;
import DAO.NoticiaDAO;
import DAO.ServidorDAO;
import Email.Email;
import Entidades.Campus;
import Entidades.Servidor;
import java.awt.Color;
import java.awt.Point;
import java.io.UnsupportedEncodingException;
import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LSA
 */
public class TelaEnviarNoticia extends javax.swing.JFrame {
    private Point point = new Point();
    
    private static final String SQL_LISTAR_TODOS = "SELECT * FROM servidores";
    private static final String SQL_LISTAR_REP = "SELECT * FROM servidores WHERE TIPO = \"Representante\"";
    private static final String SQL_LISTAR_SIN = "SELECT * FROM servidores WHERE TIPO = \"Sindicalizado\"";
    private static String sql_campus = "SELECT * FROM servidores WHERE CAMPUS = ";
    private static final String SQL_LISTAR_NSIN = "SELECT * FROM servidores WHERE TIPO = \"Não Sindicalizado\"";
    private static String sql_individual = "SELECT * FROM servidores WHERE COD = ";
    private String campusSelecionado;
    public  static String destinatario = TelaGerenciarNoticias.destinatarios;
    
    public void setCBCampus() {

        CampusDAO cdao = new CampusDAO();
        for (Campus campus : cdao.listarCampus()) {
            cbCampus.addItem(campus.getNome());

        }

    }

    public final void atualizarTabela(String SQL) {
        DefaultTableModel modelo = (DefaultTableModel) jtServidores.getModel();
        modelo.setNumRows(0);
        ServidorDAO sdao = new ServidorDAO();
        for (Servidor servidor : sdao.listarServidores(SQL)) {
            modelo.addRow(new Object[]{
                servidor.getCod(), servidor.getNome(), servidor.getEmail(), servidor.getEstado(), servidor.getCampus()

            });

        }
    }

    void enviandoNoticia(String SQL) {
        
        Email email = new Email();
        NoticiaDAO ndao = new  NoticiaDAO();
        ServidorDAO sd = new ServidorDAO();
        List<Servidor> servidores = sd.listarServidores(SQL);
        int qntServ = servidores.size();
        TelaStatusEnvio t = new TelaStatusEnvio(this, true);
        t.setVisible(true);
        
        

        new Thread() {
            @Override
            public void run() {

                try {
                    for (Servidor servidor : servidores) {
                        destinatario += servidor.getCod()+"    "+servidor.getNome()+"    "+servidor.getCampus()+"\n";
                        email.enviarEmail(TelaGerenciarNoticias.noticiaEnviadaAss, TelaGerenciarNoticias.noticiaEnviadaNot, servidor.getEmail());
                        System.out.println(qntServ);
                        System.out.println(servidores.indexOf(servidor));
                        System.out.println((servidores.indexOf(servidor) + 1) * 100);
                        t.bProgresso.setValue(((servidores.indexOf(servidor) + 1) * 100) / qntServ);
                        if (qntServ == servidores.indexOf(servidor) + 1) {
                            ndao.alterarStatus(TelaGerenciarNoticias.noticiaEnviadaCod,"Enviada", destinatario);
                            t.lImagem.setIcon(new ImageIcon(getClass().getResource("/Imagens/ok.png")));
                            t.lEnvio.setText("                        Envio Realizado com Sucesso!");
                        }
                        sleep(20);
                    }

                } catch (InterruptedException ex) {
                    System.out.println(ex);
                } catch (UnsupportedEncodingException ex) {
                    Logger.getLogger(TelaEnviarNoticia.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }.start();

    }

    public TelaEnviarNoticia() {
        initComponents();
        this.setIconImage( new ImageIcon(getClass().getResource("/Imagens/logoSDi.png")).getImage());
        atualizarTabela(SQL_LISTAR_TODOS);
        cbCampus.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgEnviarPara = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        pMinimizar = new javax.swing.JPanel();
        lMinimizar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btEnviar = new javax.swing.JButton();
        rbNsim = new javax.swing.JRadioButton();
        rbSin = new javax.swing.JRadioButton();
        rbTodos = new javax.swing.JRadioButton();
        rbRepre = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtServidores = new javax.swing.JTable();
        rbCmp = new javax.swing.JRadioButton();
        ctBusca = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        cbCampus = new javax.swing.JComboBox<>();
        rbInd = new javax.swing.JRadioButton();
        btUndo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SDi - Enviar Notícia");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setToolTipText("");

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(532, 123));

        pMinimizar.setBackground(new java.awt.Color(0, 51, 255));
        pMinimizar.setPreferredSize(new java.awt.Dimension(20, 20));
        pMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMinimizarMouseExited(evt);
            }
        });

        lMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Horizontal_Line_20px_4.png"))); // NOI18N

        javax.swing.GroupLayout pMinimizarLayout = new javax.swing.GroupLayout(pMinimizar);
        pMinimizar.setLayout(pMinimizarLayout);
        pMinimizarLayout.setHorizontalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );
        pMinimizarLayout.setVerticalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Email_Send_64px_1.png"))); // NOI18N
        jLabel5.setText(" Enviar  Notícia");

        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Back_Arrow_40px.png"))); // NOI18N
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVoltarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btVoltar)
                        .addGap(350, 350, 350)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btVoltar))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Enviar Para:");

        btEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Email_Send_16px.png"))); // NOI18N
        btEnviar.setText(" Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        rbNsim.setBackground(new java.awt.Color(255, 255, 255));
        bgEnviarPara.add(rbNsim);
        rbNsim.setText("Não Sincalizados");
        rbNsim.setActionCommand("nSin");
        rbNsim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNsimMouseClicked(evt);
            }
        });
        rbNsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNsimActionPerformed(evt);
            }
        });

        rbSin.setBackground(new java.awt.Color(255, 255, 255));
        bgEnviarPara.add(rbSin);
        rbSin.setText("Sindicalizados");
        rbSin.setActionCommand("sin");
        rbSin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbSinMouseClicked(evt);
            }
        });

        rbTodos.setBackground(new java.awt.Color(255, 255, 255));
        bgEnviarPara.add(rbTodos);
        rbTodos.setText("Todos");
        rbTodos.setActionCommand("todos");
        rbTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbTodosMouseClicked(evt);
            }
        });

        rbRepre.setBackground(new java.awt.Color(255, 255, 255));
        bgEnviarPara.add(rbRepre);
        rbRepre.setText("Representantes");
        rbRepre.setActionCommand("rep");
        rbRepre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbRepreMouseClicked(evt);
            }
        });

        jtServidores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtServidores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "E-mail", "Situação", "Campus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtServidores);

        rbCmp.setBackground(new java.awt.Color(255, 255, 255));
        bgEnviarPara.add(rbCmp);
        rbCmp.setText("Campus");
        rbCmp.setActionCommand("cmp");
        rbCmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbCmpMouseClicked(evt);
            }
        });

        ctBusca.setPreferredSize(null);
        ctBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctBuscaActionPerformed(evt);
            }
        });

        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Search_16px_5.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.setPreferredSize(null);
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        cbCampus.setMinimumSize(null);
        cbCampus.setPreferredSize(null);
        cbCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCampusActionPerformed(evt);
            }
        });

        rbInd.setBackground(new java.awt.Color(255, 255, 255));
        bgEnviarPara.add(rbInd);
        rbInd.setText("Individual");
        rbInd.setActionCommand("ind");
        rbInd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbIndMouseClicked(evt);
            }
        });
        rbInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbIndActionPerformed(evt);
            }
        });

        btUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Undo_16px_3.png"))); // NOI18N
        btUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUndoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbInd)
                            .addComponent(rbNsim)
                            .addComponent(rbSin)
                            .addComponent(rbRepre)
                            .addComponent(rbTodos)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(rbCmp)
                                .addGap(51, 51, 51)
                                .addComponent(cbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(455, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEnviar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(ctBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbTodos)
                .addGap(3, 3, 3)
                .addComponent(rbRepre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbSin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbNsim)
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCmp)
                    .addComponent(cbCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(rbInd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ctBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseClicked
        this.setState(TelaDiretor.ICONIFIED);
    }//GEN-LAST:event_pMinimizarMouseClicked

    private void pMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseEntered
        pMinimizar.setBackground(new Color(102, 102, 255));
    }//GEN-LAST:event_pMinimizarMouseEntered

    private void pMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseExited
        pMinimizar.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pMinimizarMouseExited

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed

        try {
            switch (bgEnviarPara.getSelection().getActionCommand()) {
                case "todos":

                    enviandoNoticia(SQL_LISTAR_TODOS);
                    btEnviar.setEnabled(false);
                    System.out.println("todos");
                    break;
                case "rep":

                    enviandoNoticia(SQL_LISTAR_REP);
                    rbRepre.setEnabled(false);
                    System.out.println("repre");
                    break;

                case "sin":

                    enviandoNoticia(SQL_LISTAR_SIN);
                    rbSin.setEnabled(false);
                    System.out.println("sin");
                    break;
                case "nSin":

                    enviandoNoticia(SQL_LISTAR_NSIN);
                    System.out.println("nsim");
                    rbNsim.setEnabled(false);
                    break;
                case "cmp":

                    enviandoNoticia(sql_campus);
                    System.out.println(sql_campus);
                    System.out.println("cmp");
                    break;
                case "ind":
                    if (jtServidores.getSelectedRow() != -1) {
                        int index = jtServidores.getSelectedRow();
                        sql_individual = "SELECT * FROM servidores WHERE COD = ";
                        sql_individual += "\"" +(String) jtServidores.getValueAt(index, 0)+ "\"";
                        System.out.println(sql_individual);
                        enviandoNoticia(sql_individual);
                        System.out.println("ind");

                    } else {
                        JOptionPane.showMessageDialog(null, "  Selecione um servidor", "Erro", JOptionPane.ERROR_MESSAGE);

                    }

                    break;

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione uma opção de envio", "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btEnviarActionPerformed

    private void rbNsimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNsimMouseClicked
        atualizarTabela(SQL_LISTAR_NSIN);
        cbCampus.setEnabled(false);
    }//GEN-LAST:event_rbNsimMouseClicked

    private void rbSinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbSinMouseClicked
        atualizarTabela(SQL_LISTAR_SIN);
        cbCampus.setEnabled(false);
    }//GEN-LAST:event_rbSinMouseClicked

    private void rbTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbTodosMouseClicked
        atualizarTabela(SQL_LISTAR_TODOS);
        cbCampus.setEnabled(false);
    }//GEN-LAST:event_rbTodosMouseClicked

    private void rbRepreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbRepreMouseClicked
        atualizarTabela(SQL_LISTAR_REP);
        cbCampus.setEnabled(false);
    }//GEN-LAST:event_rbRepreMouseClicked

    private void rbCmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbCmpMouseClicked
        this.setCBCampus();
        cbCampus.setEnabled(true);
    }//GEN-LAST:event_rbCmpMouseClicked

    private void ctBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctBuscaActionPerformed

    private void rbNsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNsimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNsimActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        if (ctBusca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "     Campo de busca vazio! ");
        } else {

            DefaultTableModel modelo = (DefaultTableModel) jtServidores.getModel();
            modelo.setNumRows(0);
            ServidorDAO sdao = new ServidorDAO();
            List<Servidor> buscado = new ArrayList();
            buscado = sdao.buscarServidores2(ctBusca.getText());

            if (buscado.isEmpty()) {
                JOptionPane.showMessageDialog(null, "   Servidor não existe!");
                atualizarTabela(SQL_LISTAR_TODOS);
            } else {
                for (Servidor servidor : buscado) {
                    modelo.addRow(new Object[]{
                        servidor.getCod(), servidor.getNome(), servidor.getEmail(), servidor.getEstado(), servidor.getCampus()

                    });

                }
            }

        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void cbCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCampusActionPerformed
        System.out.println(campusSelecionado);
        sql_campus = "SELECT * FROM servidores WHERE CAMPUS = ";
        campusSelecionado = " ";
        campusSelecionado += "\"" + cbCampus.getSelectedItem().toString() + "\"";
        sql_campus += campusSelecionado;
        System.out.println("2" + sql_campus);
        atualizarTabela(sql_campus);
        campusSelecionado = " ";
        //cbCampus.setVisible(true);
    }//GEN-LAST:event_cbCampusActionPerformed

    private void rbIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIndActionPerformed

    }//GEN-LAST:event_rbIndActionPerformed

    private void rbIndMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbIndMouseClicked
        atualizarTabela(SQL_LISTAR_TODOS);
        cbCampus.setEnabled(false);
    }//GEN-LAST:event_rbIndMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         point.x = evt.getX();
         point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
        TelaGerenciarNoticias obj = new TelaGerenciarNoticias();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btVoltarMouseClicked

    private void btVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseEntered
        btVoltar.setIcon(new ImageIcon(getClass().getResource("/Imagens/icons8_Back_Arrow_40px_1.png")));
    }//GEN-LAST:event_btVoltarMouseEntered

    private void btVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseExited
        btVoltar.setIcon(new ImageIcon(getClass().getResource("/Imagens/icons8_Back_Arrow_40px.png")));
    }//GEN-LAST:event_btVoltarMouseExited

    private void btUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUndoActionPerformed
        atualizarTabela(SQL_LISTAR_TODOS);
    }//GEN-LAST:event_btUndoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEnviarNoticia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEnviarNoticia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEnviarNoticia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEnviarNoticia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEnviarNoticia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgEnviarPara;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btUndo;
    private javax.swing.JLabel btVoltar;
    private javax.swing.JComboBox<String> cbCampus;
    private javax.swing.JTextField ctBusca;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtServidores;
    private javax.swing.JLabel lMinimizar;
    private javax.swing.JPanel pMinimizar;
    private javax.swing.JRadioButton rbCmp;
    private javax.swing.JRadioButton rbInd;
    private javax.swing.JRadioButton rbNsim;
    private javax.swing.JRadioButton rbRepre;
    private javax.swing.JRadioButton rbSin;
    private javax.swing.JRadioButton rbTodos;
    // End of variables declaration//GEN-END:variables
}
