/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.CampusDAO;
import Entidades.Campus;
import Utilitario.GeradorCodigos;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LSA
 */
public class TelaCadastroCampus extends javax.swing.JFrame {
 private Point point = new Point(); 
 public static String voltarPara ="";
     public void resetCampos() {
        ctNome.setText("");
        ctCodigo.setText("");
        ctLocal.setText("");
      
    }
     
     private void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) jtCampus.getModel();
        modelo.setNumRows(0);
        CampusDAO cdao = new CampusDAO();
        for (Campus campus : cdao.listarCampus()) {
            modelo.addRow(new Object[]{
                campus.getCod(), campus.getNome(), campus.getLocal()

            });

        }
    }
    public TelaCadastroCampus() {
        initComponents();
        this.setIconImage( new ImageIcon(getClass().getResource("/Imagens/logoSDi.png")).getImage());
        atualizarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        ctNome = new javax.swing.JTextField();
        ctCodigo = new javax.swing.JTextField();
        ctLocal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCampus = new javax.swing.JTable();
        btSalvar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pMinimizar = new javax.swing.JPanel();
        lMinimizar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btVoltar = new javax.swing.JLabel();
        ctBuscar = new javax.swing.JTextField();
        btAtualizar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btUndo = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SDi - Cadastrar Campus");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        ctNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctNomeActionPerformed(evt);
            }
        });

        ctCodigo.setEditable(false);
        ctCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctCodigoActionPerformed(evt);
            }
        });

        ctLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctLocalActionPerformed(evt);
            }
        });

        jtCampus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtCampus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Código", "Nome", "Local"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtCampus);

        btSalvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Save_16px_1.png"))); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Trash_16px_2.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btBuscar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Search_16px_5.png"))); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        btVisualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Eye_16px_7.png"))); // NOI18N
        btVisualizar.setText("Visualizar");
        btVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisualizarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Local:");

        jPanel7.setBackground(new java.awt.Color(0, 51, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(263, 123));

        pMinimizar.setBackground(new java.awt.Color(0, 51, 255));
        pMinimizar.setPreferredSize(new java.awt.Dimension(20, 20));
        pMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMinimizarMouseExited(evt);
            }
        });

        lMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Horizontal_Line_20px_4.png"))); // NOI18N

        javax.swing.GroupLayout pMinimizarLayout = new javax.swing.GroupLayout(pMinimizar);
        pMinimizar.setLayout(pMinimizarLayout);
        pMinimizarLayout.setHorizontalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );
        pMinimizarLayout.setVerticalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Graduation_Cap_64px_5.png"))); // NOI18N
        jLabel1.setText(" Cadastro Campus");

        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Back_Arrow_40px.png"))); // NOI18N
        btVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVoltarMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVoltarMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btVoltar)
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btVoltar))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)))
                .addGap(0, 32, Short.MAX_VALUE))
        );

        btAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Available_Updates_16px_2.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btLimpar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Erase_16px_1.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        btUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Undo_16px_3.png"))); // NOI18N
        btUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUndoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btSalvar)
                                .addGap(20, 20, 20)
                                .addComponent(btExcluir)
                                .addGap(20, 20, 20)
                                .addComponent(btAtualizar)
                                .addGap(20, 20, 20)
                                .addComponent(btVisualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btLimpar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(ctBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addComponent(btBuscar)
                        .addGap(10, 10, 10)
                        .addComponent(btUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ctLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btVisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ctBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ctNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctNomeActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_ctNomeActionPerformed

    private void ctCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctCodigoActionPerformed

    private void ctLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctLocalActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Campus campus = new Campus();
        CampusDAO cdao = new CampusDAO();
        GeradorCodigos codigo = new GeradorCodigos();
        String cod;
        do {

            cod = codigo.gerarCodigo("C");
        } while (!cdao.buscarCampus(cod).isEmpty());

        campus.setCod(cod);
        campus.setNome(ctNome.getText());
        campus.setLocal(ctLocal.getText());
        

        if ((ctNome.getText().isEmpty()) || (ctLocal.getText().isEmpty())) {

            JOptionPane.showMessageDialog(null, " Preencha todos os campos! ");
        } else {

            cdao.inserirCampus(campus);
            JOptionPane.showMessageDialog(null, "Campus cadastrado com Sucesso!", "Confirmação de Cadastro", JOptionPane.INFORMATION_MESSAGE);
            resetCampos();
            atualizarTabela();
            TelaCadastroServidor.setCBCampus();
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void pMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseClicked
        this.setState(TelaDiretor.ICONIFIED);
    }//GEN-LAST:event_pMinimizarMouseClicked

    private void pMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseEntered
        pMinimizar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_pMinimizarMouseEntered

    private void pMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseExited
        pMinimizar.setBackground(new Color(0,51,255));
    }//GEN-LAST:event_pMinimizarMouseExited

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
       if (jtCampus.getSelectedRow() != -1) {

            Campus campus = new Campus();
            CampusDAO c = new CampusDAO();

            int index = jtCampus.getSelectedRow();

            campus.setCod((String) jtCampus.getValueAt(index, 0));
            campus.setNome((String) jtCampus.getValueAt(index, 1));
            campus.setLocal((String) jtCampus.getValueAt(index, 2));
            

            c.deletarCampus(campus);
            JOptionPane.showMessageDialog(null, "Campus excluído com Sucesso!", "Confirmação de Exclusão", JOptionPane.INFORMATION_MESSAGE);
            resetCampos();
            btSalvar.setEnabled(true);
            atualizarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "   Selecione um Campus", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        if ((ctNome.getText().isEmpty()) || (ctLocal.getText().isEmpty())) {

            JOptionPane.showMessageDialog(null, " Preencha todos os campos! ");
        } else {
            
            Campus campus = new Campus();
            CampusDAO c = new CampusDAO();
            

            campus.setCod(ctCodigo.getText());;
            campus.setNome(ctNome.getText());
            campus.setLocal(ctLocal.getText());
            
            if (!c.buscarCampus(ctCodigo.getText()).isEmpty()) {
                c.alterarCampus(campus);
                JOptionPane.showMessageDialog(null, "Campus atualizado com Sucesso!", "Confirmação de Atualização", JOptionPane.INFORMATION_MESSAGE);
                resetCampos();
                btSalvar.setEnabled(true);
                atualizarTabela();
            } else {

                JOptionPane.showMessageDialog(null, " Atualização não realizada, Campus não existe!");

            }

        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisualizarActionPerformed
       if (jtCampus.getSelectedRow() != -1) {
            int index = jtCampus.getSelectedRow();
            String cod = (String) jtCampus.getValueAt(index, 0);
            String nome = (String) jtCampus.getValueAt(index, 1);
            String campus = (String) jtCampus.getValueAt(index, 2);
            ctCodigo.setText(cod);
            ctNome.setText(nome);
            ctLocal.setText(campus);
            btSalvar.setEnabled(false);
            
        } else {
            JOptionPane.showMessageDialog(null, "  Selecione um Campus", "Erro", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
         if (ctBuscar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "     Campo de busca vazio! ");
        } else {

            DefaultTableModel modelo = (DefaultTableModel) jtCampus.getModel();
            modelo.setNumRows(0);
            CampusDAO cdao = new CampusDAO();
            List<Campus> buscado = new ArrayList();
            buscado = cdao.buscarCampus2(ctBuscar.getText());

            if (buscado.isEmpty()) {
                JOptionPane.showMessageDialog(null, "   Campus não existe!");
                atualizarTabela();
            } else {
                for (Campus campus : buscado) {
                    modelo.addRow(new Object[]{
                        campus.getCod(), campus.getNome(), campus.getLocal(), 

                    });

                }
            }

        }
    }//GEN-LAST:event_btBuscarActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
       point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    private void btVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseEntered
        btVoltar.setIcon(new ImageIcon(getClass().getResource("/Imagens/icons8_Back_Arrow_40px_1.png")));
    }//GEN-LAST:event_btVoltarMouseEntered

    private void btVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseExited
         btVoltar.setIcon(new ImageIcon(getClass().getResource("/Imagens/icons8_Back_Arrow_40px.png")));
    }//GEN-LAST:event_btVoltarMouseExited

    private void btVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVoltarMouseClicked
       if(voltarPara.equals("principal")){
        TelaDiretor obj = new TelaDiretor();
        obj.setVisible(true);
        this.dispose();
        voltarPara ="";
        }else{
        this.dispose();
        }
    }//GEN-LAST:event_btVoltarMouseClicked

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        resetCampos();
        btSalvar.setEnabled(true);
        
    }//GEN-LAST:event_btLimparActionPerformed

    private void btUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUndoActionPerformed
        atualizarTabela();
    }//GEN-LAST:event_btUndoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroCampus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroCampus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton btUndo;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JLabel btVoltar;
    private javax.swing.JTextField ctBuscar;
    private javax.swing.JTextField ctCodigo;
    private javax.swing.JTextField ctLocal;
    private javax.swing.JTextField ctNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCampus;
    private javax.swing.JLabel lMinimizar;
    private javax.swing.JPanel pMinimizar;
    // End of variables declaration//GEN-END:variables
}
