/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utilitario.JPassWordFieldHint;
import ConexaoDB.ConectarBD;
import Entidades.Usuario;
import java.awt.Color;
import java.awt.Point;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author LSA
 */
public class TelaAlterarSenha extends javax.swing.JFrame {
     private Point point = new Point();    
     private static final String SQL_ALTERAR_SENHA = "UPDATE usuarios SET senha = ? WHERE login = ?";
     public static boolean abrirTelaLogin = false;
    public void alterarSenha(String SQL) {
        Connection con = null;
        PreparedStatement smts = null;
        ResultSet rs = null;
        Usuario usuario = new Usuario();

        usuario.setSenha(cpNovaSenha.getText());
        usuario.setLogin(TelaLogin.loginAtual);

        if ((cpSenhaAtual.getText().isEmpty()) || (cpNovaSenha.getText().isEmpty()) || (cpSenhaAtual.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Há campos vazios");
        } else {
            if (cpSenhaAtual.getText().equals(TelaLogin.senhaAtual)) {

                if (cpNovaSenha.getText().equals(TelaLogin.senhaAtual)) {

                    JOptionPane.showMessageDialog(null, "Senha igual a anterior!!");

                } else {
                    if (cpNovaSenha.getText().equals(cpConfirmar1.getText())) {
                        
                        try {
                            con = ConectarBD.conectar();
                            smts = (PreparedStatement) con.prepareStatement(SQL);
                            smts.setString(1, usuario.getSenha());
                            smts.setString(2,usuario.getLogin() );
                            smts.execute();
                            TelaLogin.senhaAtual = cpNovaSenha.getText().toString();
                            JOptionPane.showMessageDialog(null, "Senha alterada com sucesso");
                            if(abrirTelaLogin){
                              TelaLogin tl = new TelaLogin();
                              tl.setVisible(true);
                            }
                            this.dispose();
                        } catch (SQLException e) {

                            e.printStackTrace();
                        } finally {
                            ConectarBD.desconectar(con, smts, rs);

                        }

                    } else {

                        JOptionPane.showMessageDialog(null, "Os campos : Senha e Confirmar Senha  estão diferentes");

                    }

                }
            } else {

                JOptionPane.showMessageDialog(null, "A senha atual informada está incorreta!");
                cpSenhaAtual.setText("");
            }

        }

    }

    public TelaAlterarSenha() {
        initComponents();
        this.setIconImage( new ImageIcon(getClass().getResource("/Imagens/logoSDi.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pMinimizar = new javax.swing.JPanel();
        lMinimizar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cpNovaSenha =  new JPassWordFieldHint( new JPasswordField(),"padlock","Nova Senha")
  ;
        bAlterar = new javax.swing.JButton();
        bSair = new javax.swing.JButton();
        cpSenhaAtual =  new JPassWordFieldHint( new JPasswordField(),"padlock","Senha Atual")
  ;
        btVer1 = new javax.swing.JToggleButton();
        cpConfirmar1 =  new JPassWordFieldHint( new JPasswordField(),"padlock","Confirmar Nova Senha")
  ;

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SDi - Alterar Senha");
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 123));

        pMinimizar.setBackground(new java.awt.Color(0, 51, 255));
        pMinimizar.setPreferredSize(new java.awt.Dimension(20, 20));
        pMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMinimizarMouseExited(evt);
            }
        });

        lMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Horizontal_Line_20px_4.png"))); // NOI18N

        javax.swing.GroupLayout pMinimizarLayout = new javax.swing.GroupLayout(pMinimizar);
        pMinimizar.setLayout(pMinimizarLayout);
        pMinimizarLayout.setHorizontalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );
        pMinimizarLayout.setVerticalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Key_64px_1.png"))); // NOI18N
        jLabel5.setText(" Alterar Senha");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel5)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        cpNovaSenha.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        cpNovaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpNovaSenhaActionPerformed(evt);
            }
        });

        bAlterar.setBackground(new java.awt.Color(58, 65, 84));
        bAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bAlterar.setForeground(new java.awt.Color(255, 255, 255));
        bAlterar.setText("Alterar");
        bAlterar.setBorderPainted(false);
        bAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bAlterar.setFocusPainted(false);
        bAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bAlterarMouseExited(evt);
            }
        });
        bAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlterarActionPerformed(evt);
            }
        });

        bSair.setBackground(new java.awt.Color(235, 81, 51));
        bSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bSair.setForeground(new java.awt.Color(255, 255, 255));
        bSair.setText("Sair");
        bSair.setBorderPainted(false);
        bSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bSair.setFocusPainted(false);
        bSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSairMouseExited(evt);
            }
        });
        bSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSairActionPerformed(evt);
            }
        });

        cpSenhaAtual.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        cpSenhaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpSenhaAtualActionPerformed(evt);
            }
        });

        btVer1.setBackground(new java.awt.Color(255, 255, 255));
        btVer1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ver.png"))); // NOI18N
        btVer1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btVer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVer1ActionPerformed(evt);
            }
        });

        cpConfirmar1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        cpConfirmar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpConfirmar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cpConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(btVer1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cpSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(cpSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(cpNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btVer1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpConfirmar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(bAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 123, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cpNovaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpNovaSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpNovaSenhaActionPerformed

    private void bAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAlterarMouseEntered
        bAlterar.setBackground(new Color(235, 235, 235));
        bAlterar.setForeground(new Color(58, 65, 85));
    }//GEN-LAST:event_bAlterarMouseEntered

    private void bAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAlterarMouseExited
        bAlterar.setBackground(new Color(58, 65, 85));
        bAlterar.setForeground(Color.WHITE);
    }//GEN-LAST:event_bAlterarMouseExited

    private void bAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlterarActionPerformed
        Point p = this.getLocation();
        TelaAlterarSenha aSenha = this;

        new Thread() {
            @Override
            public void run() {

                try {
                    for (int i = 0; i < 6; i++) {
                        aSenha.setLocation(p.x + 10, p.y);
                        sleep(20);
                        aSenha.setLocation(p.x - 10, p.y);
                        sleep(20);

                    }
                    aSenha.setLocation(p.x, p.y);
                } catch (InterruptedException ex) {
                    Logger.getLogger(TelaLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }.start();

        alterarSenha(SQL_ALTERAR_SENHA);


    }//GEN-LAST:event_bAlterarActionPerformed

    private void bSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseEntered
        bSair.setBackground(new Color(235, 235, 235));
        bSair.setForeground(new Color(217, 81, 51));
    }//GEN-LAST:event_bSairMouseEntered

    private void bSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSairMouseExited
        bSair.setBackground(new Color(217, 81, 51));
        bSair.setForeground(Color.WHITE);
    }//GEN-LAST:event_bSairMouseExited

    private void bSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_bSairActionPerformed

    private void cpSenhaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpSenhaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpSenhaAtualActionPerformed

    private void pMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseClicked
        this.setState(TelaDiretor.ICONIFIED);
    }//GEN-LAST:event_pMinimizarMouseClicked

    private void pMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseEntered
        pMinimizar.setBackground(new Color(102, 102, 255));
    }//GEN-LAST:event_pMinimizarMouseEntered

    private void pMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseExited
        pMinimizar.setBackground(new Color(0, 51, 255));
    }//GEN-LAST:event_pMinimizarMouseExited

    private void btVer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVer1ActionPerformed

        if( cpNovaSenha.echoCharIsSet()){
           btVer1.setIcon(new ImageIcon(getClass().getResource("/Imagens/nver.png")));
            cpSenhaAtual.setEchoChar('\u0000');
            cpNovaSenha.setEchoChar('\u0000');
            cpConfirmar1.setEchoChar('\u0000');
        }else{
            btVer1.setIcon(new ImageIcon(getClass().getResource("/Imagens/ver.png")));
            cpSenhaAtual.setEchoChar('\u25cf');
            cpNovaSenha.setEchoChar('\u25cf');
            cpConfirmar1.setEchoChar('\u25cf');

        }
    }//GEN-LAST:event_btVer1ActionPerformed

    private void cpConfirmar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpConfirmar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpConfirmar1ActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        point.x = evt.getX();
        point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point p = this.getLocation();
        this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAlterarSenha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAlterarSenha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlterar;
    private javax.swing.JButton bSair;
    private javax.swing.JToggleButton btVer1;
    private javax.swing.JPasswordField cpConfirmar1;
    private javax.swing.JPasswordField cpNovaSenha;
    private javax.swing.JPasswordField cpSenhaAtual;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lMinimizar;
    private javax.swing.JPanel pMinimizar;
    // End of variables declaration//GEN-END:variables
}
