/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Point;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author LSA
 */
public class TelaEditor extends javax.swing.JFrame {
 private Point point = new Point();
    /**
     * Creates new form TelaEditor
     */
    public TelaEditor() {
        initComponents();
        this.setIconImage( new ImageIcon(getClass().getResource("/Imagens/logoSDi.png")).getImage());
        
        
    }
    
     public void setCorPanel(JPanel p, JLabel l){
        
     p.setBackground(new Color (115,163,239));
     l.setForeground(new Color(255,255,255));
    }
    
     public void resetCorPanel(JPanel p,JLabel l){
        
     p.setBackground(new Color (240,240,240));
     l.setForeground(new Color(0,0,0));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pSolicitacoes = new javax.swing.JPanel();
        lSolicitacoes = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pEditar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lEditar = new javax.swing.JLabel();
        pHistorico = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lHistorico = new javax.swing.JLabel();
        pAlterarSenha = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lAlterarSenha = new javax.swing.JLabel();
        pLogOut = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lLogOut = new javax.swing.JLabel();
        pSobre = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lSobre = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pSair1 = new javax.swing.JPanel();
        lSair1 = new javax.swing.JLabel();
        pMinimizar = new javax.swing.JPanel();
        lMinimizar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SDi - Tela Inicial Editor");
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(127, 120));

        pSolicitacoes.setEnabled(false);
        pSolicitacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSolicitacoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pSolicitacoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pSolicitacoesMouseExited(evt);
            }
        });

        lSolicitacoes.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lSolicitacoes.setText("Solicitações");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Ask_Question_64px.png"))); // NOI18N

        javax.swing.GroupLayout pSolicitacoesLayout = new javax.swing.GroupLayout(pSolicitacoes);
        pSolicitacoes.setLayout(pSolicitacoesLayout);
        pSolicitacoesLayout.setHorizontalGroup(
            pSolicitacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSolicitacoesLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(pSolicitacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSolicitacoesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSolicitacoesLayout.createSequentialGroup()
                        .addComponent(lSolicitacoes)
                        .addGap(26, 26, 26))))
        );
        pSolicitacoesLayout.setVerticalGroup(
            pSolicitacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSolicitacoesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lSolicitacoes)
                .addContainerGap())
        );

        pEditar.setPreferredSize(new java.awt.Dimension(142, 125));
        pEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pEditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pEditarMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Edit_64px_7.png"))); // NOI18N

        lEditar.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lEditar.setText("Editar");

        javax.swing.GroupLayout pEditarLayout = new javax.swing.GroupLayout(pEditar);
        pEditar.setLayout(pEditarLayout);
        pEditarLayout.setHorizontalGroup(
            pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lEditar))
                    .addComponent(jLabel7))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        pEditarLayout.setVerticalGroup(
            pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lEditar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pHistorico.setPreferredSize(new java.awt.Dimension(142, 125));
        pHistorico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pHistoricoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pHistoricoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pHistoricoMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Time_Machine_64px_1.png"))); // NOI18N

        lHistorico.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        lHistorico.setText("Histórico de Notícias");

        javax.swing.GroupLayout pHistoricoLayout = new javax.swing.GroupLayout(pHistorico);
        pHistorico.setLayout(pHistoricoLayout);
        pHistoricoLayout.setHorizontalGroup(
            pHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHistoricoLayout.createSequentialGroup()
                .addGroup(pHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pHistoricoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8))
                    .addGroup(pHistoricoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lHistorico)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pHistoricoLayout.setVerticalGroup(
            pHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHistoricoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lHistorico)
                .addContainerGap())
        );

        pAlterarSenha.setPreferredSize(new java.awt.Dimension(142, 125));
        pAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pAlterarSenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pAlterarSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pAlterarSenhaMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Key_64px_2.png"))); // NOI18N

        lAlterarSenha.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lAlterarSenha.setText("Alterar Senha");

        javax.swing.GroupLayout pAlterarSenhaLayout = new javax.swing.GroupLayout(pAlterarSenha);
        pAlterarSenha.setLayout(pAlterarSenhaLayout);
        pAlterarSenhaLayout.setHorizontalGroup(
            pAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlterarSenhaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pAlterarSenhaLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lAlterarSenha)
                .addGap(22, 22, 22))
        );
        pAlterarSenhaLayout.setVerticalGroup(
            pAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAlterarSenhaLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lAlterarSenha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pLogOut.setPreferredSize(new java.awt.Dimension(142, 125));
        pLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pLogOutMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Sign_Out_64px_1.png"))); // NOI18N

        lLogOut.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lLogOut.setText("Log Out");

        javax.swing.GroupLayout pLogOutLayout = new javax.swing.GroupLayout(pLogOut);
        pLogOut.setLayout(pLogOutLayout);
        pLogOutLayout.setHorizontalGroup(
            pLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLogOutLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(pLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(lLogOut))
                .addGap(38, 38, 38))
        );
        pLogOutLayout.setVerticalGroup(
            pLogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLogOutLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lLogOut)
                .addContainerGap())
        );

        pSobre.setPreferredSize(new java.awt.Dimension(142, 125));
        pSobre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSobreMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pSobreMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pSobreMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Info_64px.png"))); // NOI18N

        lSobre.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lSobre.setText("Sobre");

        javax.swing.GroupLayout pSobreLayout = new javax.swing.GroupLayout(pSobre);
        pSobre.setLayout(pSobreLayout);
        pSobreLayout.setHorizontalGroup(
            pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSobreLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pSobreLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lSobre))
                    .addComponent(jLabel9))
                .addGap(36, 36, 36))
        );
        pSobreLayout.setVerticalGroup(
            pSobreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSobreLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lSobre)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(0, 51, 255));

        pSair1.setBackground(new java.awt.Color(0, 51, 255));
        pSair1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pSair1MouseClicked(evt);
            }
        });

        lSair1.setBackground(new java.awt.Color(255, 0, 0));
        lSair1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lSair1.setForeground(new java.awt.Color(255, 255, 255));
        lSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Delete_20px.png"))); // NOI18N
        lSair1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lSair1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lSair1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lSair1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pSair1Layout = new javax.swing.GroupLayout(pSair1);
        pSair1.setLayout(pSair1Layout);
        pSair1Layout.setHorizontalGroup(
            pSair1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSair1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lSair1))
        );
        pSair1Layout.setVerticalGroup(
            pSair1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lSair1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pMinimizar.setBackground(new java.awt.Color(0, 51, 255));
        pMinimizar.setPreferredSize(new java.awt.Dimension(20, 20));
        pMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMinimizarMouseExited(evt);
            }
        });

        lMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8_Horizontal_Line_20px_4.png"))); // NOI18N

        javax.swing.GroupLayout pMinimizarLayout = new javax.swing.GroupLayout(pMinimizar);
        pMinimizar.setLayout(pMinimizarLayout);
        pMinimizarLayout.setHorizontalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );
        pMinimizarLayout.setVerticalGroup(
            pMinimizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMinimizarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lMinimizar))
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tela Inicial");

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/teste3.png"))); // NOI18N
        jLabel11.setFocusCycleRoot(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(pSair1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(65, 65, 65))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pSair1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSolicitacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pSolicitacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pAlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pSolicitacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSolicitacoesMouseClicked
        TelaSolicitacoes obj = new TelaSolicitacoes();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pSolicitacoesMouseClicked

    private void pSolicitacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSolicitacoesMouseEntered
        setCorPanel(pSolicitacoes,lSolicitacoes);
    }//GEN-LAST:event_pSolicitacoesMouseEntered

    private void pSolicitacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSolicitacoesMouseExited
        resetCorPanel(pSolicitacoes,lSolicitacoes);
    }//GEN-LAST:event_pSolicitacoesMouseExited

    private void pEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEditarMouseEntered
        setCorPanel(pEditar,lEditar);
    }//GEN-LAST:event_pEditarMouseEntered

    private void pEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEditarMouseExited
        resetCorPanel(pEditar,lEditar);
    }//GEN-LAST:event_pEditarMouseExited

    private void pHistoricoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHistoricoMouseEntered
        setCorPanel(pHistorico,lHistorico);
    }//GEN-LAST:event_pHistoricoMouseEntered

    private void pHistoricoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHistoricoMouseExited
        resetCorPanel(pHistorico,lHistorico);
    }//GEN-LAST:event_pHistoricoMouseExited

    private void pAlterarSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAlterarSenhaMouseEntered
        setCorPanel(pAlterarSenha,lAlterarSenha);
    }//GEN-LAST:event_pAlterarSenhaMouseEntered

    private void pAlterarSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAlterarSenhaMouseExited
        resetCorPanel(pAlterarSenha,lAlterarSenha);
    }//GEN-LAST:event_pAlterarSenhaMouseExited

    private void pLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLogOutMouseEntered
        setCorPanel(pLogOut,lLogOut);
    }//GEN-LAST:event_pLogOutMouseEntered

    private void pLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLogOutMouseExited
        resetCorPanel(pLogOut,lLogOut);
    }//GEN-LAST:event_pLogOutMouseExited

    private void pSobreMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSobreMouseEntered
        setCorPanel(pSobre,lSobre);
    }//GEN-LAST:event_pSobreMouseEntered

    private void pSobreMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSobreMouseExited
        resetCorPanel(pSobre,lSobre);
    }//GEN-LAST:event_pSobreMouseExited

    private void pAlterarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pAlterarSenhaMouseClicked
        TelaAlterarSenha obj = new TelaAlterarSenha();
        obj.setVisible(true);
    }//GEN-LAST:event_pAlterarSenhaMouseClicked

    private void pSobreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSobreMouseClicked
        TelaSobre obj = new TelaSobre();
        obj.setVisible(true);
    }//GEN-LAST:event_pSobreMouseClicked

    private void pEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pEditarMouseClicked
        TelaEditarNoticia obj = new TelaEditarNoticia();
        obj.setVisible(true);
        this.dispose();
        TelaEditarNoticia.voltarPara = "principal";
    }//GEN-LAST:event_pEditarMouseClicked

    private void pHistoricoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHistoricoMouseClicked
        TelaHistoricoNoticias obj = new TelaHistoricoNoticias();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pHistoricoMouseClicked

    private void lSair1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSair1MouseClicked
        this.dispose();
    }//GEN-LAST:event_lSair1MouseClicked

    private void lSair1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSair1MouseEntered
        pSair1.setBackground(new Color(204,0,0));
    }//GEN-LAST:event_lSair1MouseEntered

    private void lSair1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lSair1MouseExited
        pSair1.setBackground(new Color(0,51,255));
    }//GEN-LAST:event_lSair1MouseExited

    private void pSair1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSair1MouseClicked
        this.dispose();
    }//GEN-LAST:event_pSair1MouseClicked

    private void pMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseClicked
        this.setState(TelaDiretor.ICONIFIED);
    }//GEN-LAST:event_pMinimizarMouseClicked

    private void pMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseEntered
        pMinimizar.setBackground(new Color(102,102,255));
    }//GEN-LAST:event_pMinimizarMouseEntered

    private void pMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMinimizarMouseExited
        pMinimizar.setBackground(new Color(0,51,255));
    }//GEN-LAST:event_pMinimizarMouseExited

    private void pLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pLogOutMouseClicked
       TelaLogin.senhaAtual ="";
       TelaLogin.loginAtual = "";
       TelaLogin obj = new  TelaLogin();
       this.dispose();
       obj.setVisible(true);
       
    }//GEN-LAST:event_pLogOutMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
          point.x = evt.getX();
          point.y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
         Point p = this.getLocation();
         this.setLocation(p.x + evt.getX() - point.x, p.y + evt.getY() - point.y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lAlterarSenha;
    private javax.swing.JLabel lEditar;
    private javax.swing.JLabel lHistorico;
    private javax.swing.JLabel lLogOut;
    private javax.swing.JLabel lMinimizar;
    private javax.swing.JLabel lSair1;
    private javax.swing.JLabel lSobre;
    private javax.swing.JLabel lSolicitacoes;
    private javax.swing.JPanel pAlterarSenha;
    private javax.swing.JPanel pEditar;
    private javax.swing.JPanel pHistorico;
    private javax.swing.JPanel pLogOut;
    private javax.swing.JPanel pMinimizar;
    private javax.swing.JPanel pSair1;
    private javax.swing.JPanel pSobre;
    private javax.swing.JPanel pSolicitacoes;
    // End of variables declaration//GEN-END:variables
}
